Repository egc-veleta-g1/decide, pull requests merged in 2021-12, with the labels that each got.

#3 Implementar la configuración para la Integración Continua
  .github/workflows/django.yml
  Procfile
  decide/decide/settings.py
  requirements.txt
Labels: conf, high priority

#4 Implementar la configuración para la Integración Continua
  .github/workflows/django.yml
  Procfile
  decide/decide/settings.py
  requirements.txt
Labels: conf, high priority

#17 Feature/6 pagina modulo visualizer
  decide/visualizer/templates/visualizer/inicio.html
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: feature

#20 Arreglar enlace visualización en inicio
  decide/base/templates/inicio.html
  decide/visualizer/templates/visualizer/inicio.html
  decide/visualizer/urls.py
Labels: high priority, fix

#21 feat : Crear gráfica de resultados de votación #9
  decide/booth/static/js/grafica_visualizer.js
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/views.py
Labels: feature, medium priority

#22 test : Añadir test para votación no existente #6
  decide/visualizer/migrations/datos_prueba.json
  decide/visualizer/tests.py
Labels: feature, medium priority

#25 fix : Refactorizar estilos de código para codacy #24
  decide/booth/static/booth/style.css
  decide/visualizer/tests.py
  decide/visualizer/views.py
Labels: fix, low priority
