Repository egc-veleta-g1/decide, pull requests merged in 2022-01, with the labels that each got.

#48 Develop
  decide/booth/static/booth/style.css
  decide/decide/settings.py
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/visualizer/selenium/test_inicio_visualizer.py
  decide/visualizer/templates/visualizer/inicio.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/views.py
  requirements.txt
Labels: feature, low priority

#59 fix : Arreglar NavBar
  decide/base/templates/base.html
Labels: change request, fix, low priority

#71 Feature/38 tests pagina inicio
  decide/visualizer/selenium/testPaginaPrincipal.py
Labels: feature, medium priority

#73 feature : Añadir titulo a página de votación #72
  decide/visualizer/templates/visualizer/visualizer.html
Labels: feature, medium priority

#75 feature : Añadir Tests Postprocesado #74
  decide/postproc/tests.py
Labels: feature, medium priority

#77 test : Añadir Tests Selenium Votacion #76
  decide/visualizer/selenium/test_pagina_votacion.py
Labels: feature, medium priority
